apiVersion: v1
kind: Service
metadata:
  name: freeswitch
  namespace: ai-receptionist
spec:
  type: NodePort
  ports:
    - port: 5060
      targetPort: 5060
      protocol: UDP
      name: sip
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: websocket
  selector:
    app: freeswitch