apiVersion: v1
kind: ConfigMap
metadata:
  name: freeswitch-config
  namespace: ai-receptionist
data:
  sofia.conf.xml: |
    <!-- sofia.conf.xml -->
    <configuration name="sofia.conf" description="sofia Endpoint">
      <profiles>
        <profile name="ai_receptionist">
          <settings>
            <param name="debug" value="0"/>
            <param name="sip-trace" value="no"/>
            <param name="rfc2833-pt" value="101"/>
            <param name="sip-port" value="5060"/>
            <param name="dialplan" value="XML"/>
            <param name="context" value="ai_receptionist"/>
            <param name="dtmf-duration" value="2000"/>
            <param name="inbound-codec-prefs" value="PCMU,PCMA,GSM"/>
            <param name="outbound-codec-prefs" value="PCMU,PCMA,GSM"/>
            <param name="hold-music" value="$${hold_music}"/>
            <param name="rtp-timer-name" value="soft"/>
            <param name="local-network-acl" value="localnet.auto"/>
            <param name="manage-presence" value="false"/>
            <param name="inbound-codec-negotiation" value="generous"/>
            <param name="nonce-ttl" value="60"/>
            <param name="auth-calls" value="true"/>
            <param name="accept-blind-reg" value="false"/>
            <param name="accept-blind-auth" value="false"/>
            <param name="auth-all-packets" value="false"/>
            <param name="ext-rtp-ip" value="auto-nat"/>
            <param name="ext-sip-ip" value="auto-nat"/>
            <param name="rtp-ip" value="auto"/>
            <param name="sip-ip" value="auto"/>
            <!-- Directory lookup via HTTP -->
            <param name="xml-user-directory" value="true"/>
            <param name="xml-user-directory-cache" value="false"/>
          </settings>
        </profile>
      </profiles>
    </configuration>
  ai_receptionist.xml: |
    <!-- dialplan/ai_receptionist.xml -->
    <include>
      <context name="ai_receptionist">
        <extension name="ai_receptionist_incoming">
          <condition field="destination_number" expression="^(ai_receptionist|1000)$">
            <action application="set" data="call_timeout=30"/>
            <action application="set" data="hangup_after_bridge=true"/>
            <action application="answer"/>
            <action application="sleep" data="1000"/>
            <action application="socket" data="localhost:8080 async full"/>
            <action application="playback" data="ivr/ivr-thank_you_for_calling.wav"/>
            <action application="playback" data="ivr/ivr-please_hold_while_we_transfer_your_call.wav"/>
            <action application="transfer" data="operator"/>
          </condition>
        </extension>
        <extension name="operator_transfer">
          <condition field="destination_number" expression="^operator$">
            <action application="bridge" data="user/operator@$${domain_name}"/>
            <action application="hangup"/>
          </condition>
        </extension>
        <extension name="voicemail">
          <condition field="destination_number" expression="^voicemail$">
            <action application="voicemail" data="default $${domain_name} 1000"/>
          </condition>
        </extension>
      </context>
    </include>
  event_socket.conf.xml: |
    <!-- autoload_configs/event_socket.conf.xml -->
    <configuration name="event_socket.conf" description="Socket Client">
      <settings>
        <param name="nat-map" value="false"/>
        <param name="listen-ip" value="0.0.0.0"/>
        <param name="listen-port" value="8021"/>
        <param name="password" value="ClueCon"/>
        <param name="apply-inbound-acl" value="loopback.auto"/>
      </settings>
    </configuration>
  switch.conf.xml: |
    <!-- autoload_configs/switch.conf.xml -->
    <configuration name="switch.conf" description="Core Configuration">
      <settings>
        <param name="colorize-console" value="true"/>
        <param name="max-sessions" value="1000"/>
        <param name="sessions-per-second" value="30"/>
        <param name="loglevel" value="info"/>
        <param name="rtp-start-port" value="16384"/>
        <param name="rtp-end-port" value="32768"/>
      </settings>
    </configuration>
  modules.conf.xml: |
    <configuration name="modules.conf" description="Modules">
      <modules>
        <!-- Loggers (I'd load these first) -->
        <load module="mod_console"/>
        <!-- <load module="mod_graylog2"/> -->
        <load module="mod_logfile"/>
        <!-- <load module="mod_syslog"/> -->

        <!--<load module="mod_yaml"/>-->

        <!-- Multi-Faceted -->
        <!-- mod_enum is a dialplan interface, an application interface and an api command interface -->
        <load module="mod_enum"/>

        <!-- XML Interfaces -->
        <!-- <load module="mod_xml_rpc"/> -->
        <load module="mod_xml_curl"/>
        <!-- <load module="mod_xml_cdr"/> -->
        <!-- <load module="mod_xml_radius"/> -->
        <!-- <load module="mod_xml_scgi"/> -->

        <!-- Event Handlers -->
        <!-- <load module="mod_amqp"/> -->
        <load module="mod_cdr_csv"/>
        <!-- <load module="mod_cdr_sqlite"/> -->
        <!-- <load module="mod_event_multicast"/> -->
        <load module="mod_event_socket"/>
        <!-- <load module="mod_event_zmq"/> -->
        <!-- <load module="mod_zeroconf"/> -->
        <!-- <load module="mod_erlang_event"/> -->
        <!-- <load module="mod_smpp"/> -->
        <!-- <load module="mod_snmp"/> -->

        <!-- Directory Interfaces -->
        <!-- <load module="mod_ldap"/> -->

        <!-- Endpoints -->
        <!-- <load module="mod_dingaling"/> -->
        <!-- <load module="mod_portaudio"/> -->
        <!-- <load module="mod_alsa"/> -->
        <load module="mod_sofia"/>
        <load module="mod_loopback"/>
        <!-- <load module="mod_woomera"/> -->
        <!-- <load module="mod_freetdm"/> -->
        <!-- <load module="mod_unicall"/> -->
        <!-- <load module="mod_skinny"/> -->
        <!-- <load module="mod_khomp"/>   -->
        <load module="mod_rtc"/>
        <!-- <load module="mod_rtmp"/>   -->
        <load module="mod_verto"/>

        <!-- Applications -->
        <load module="mod_signalwire"/>
        <load module="mod_commands"/>
        <load module="mod_conference"/>
        <!-- <load module="mod_curl"/> -->
        <load module="mod_db"/>
        <load module="mod_dptools"/>
        <load module="mod_expr"/>
        <load module="mod_fifo"/>
        <load module="mod_hash"/>
        <!--<load module="mod_mongo"/> -->
        <load module="mod_voicemail"/>
        <!--<load module="mod_directory"/>-->
        <!--<load module="mod_distributor"/>-->
        <!--<load module="mod_lcr"/>-->
        <!--<load module="mod_easyroute"/>-->
        <load module="mod_esf"/>
        <load module="mod_fsv"/>
        <!--<load module="mod_cluechoo"/>-->
        <load module="mod_valet_parking"/>
        <!--<load module="mod_fsk"/>-->
        <!--<load module="mod_spy"/>-->
        <!--<load module="mod_sms"/>-->
        <!--<load module="mod_sms_flowroute"/>-->
        <!--<load module="mod_smpp"/>-->
        <!--<load module="mod_random"/>-->
        <load module="mod_httapi"/>
        <!--<load module="mod_translate"/>-->

        <!-- SNOM Module -->
        <!--<load module="mod_snom"/>-->

        <!-- This one only works on Linux for now -->
        <!--<load module="mod_ladspa"/>-->

        <!-- Dialplan Interfaces -->
        <!-- <load module="mod_dialplan_directory"/> -->
        <load module="mod_dialplan_xml"/>
        <load module="mod_dialplan_asterisk"/>

        <!-- Codec Interfaces -->
        <load module="mod_spandsp"/>
        <load module="mod_g723_1"/>
        <load module="mod_g729"/>
        <load module="mod_amr"/>
        <!--<load module="mod_ilbc"/>-->
        <!--<load module="mod_h26x"/>-->
        <load module="mod_b64"/>
        <!--<load module="mod_siren"/>-->
        <!--<load module="mod_isac"/>-->
        <load module="mod_opus"/>

        <!-- File Format Interfaces -->
        <load module="mod_av"/>
        <load module="mod_sndfile"/>
        <load module="mod_native_file"/>
        <!--<load module="mod_opusfile"/>-->
        <load module="mod_png"/>
        <!-- <load module="mod_shell_stream"/> -->
        <!--For icecast/mp3 streams/files-->
        <!--<load module="mod_shout"/>-->
        <!--For local streams (play all the files in a directory)-->
        <load module="mod_local_stream"/>
        <load module="mod_tone_stream"/>

        <!-- Timers -->
        <!-- <load module="mod_timerfd"/> -->
        <!-- <load module="mod_posix_timer"/> -->

        <!-- Languages -->
        <!-- <load module="mod_v8"/> -->
        <!-- <load module="mod_perl"/> -->
        <!-- <load module="mod_python"/> -->
        <!-- <load module="mod_python3"/> -->
        <!-- <load module="mod_java"/> -->
        <load module="mod_lua"/>

        <!-- ASR /TTS -->
        <!-- <load module="mod_flite"/> -->
        <!-- <load module="mod_pocketsphinx"/> -->
        <!-- <load module="mod_cepstral"/> -->
        <!-- <load module="mod_tts_commandline"/> -->
        <!-- <load module="mod_rss"/> -->

        <!-- Say -->
        <load module="mod_say_en"/>
        <!-- <load module="mod_say_ru"/> -->
        <!-- <load module="mod_say_zh"/> -->
        <!-- <load module="mod_say_sv"/> -->

        <!-- Third party modules -->
        <!--<load module="mod_nibblebill"/>-->
        <!--<load module="mod_callcenter"/>-->
      </modules>
    </configuration>
  xml_curl.conf.xml: |
    <configuration name="xml_curl.conf" description="cURL XML Gateway">
      <bindings>
        <binding name="directory">
          <param name="gateway-url" value="http://backend-api:3000/api/v1/freeswitch/directory" bindings="directory"/>
          <param name="method" value="POST"/>
        </binding>
        <binding name="dialplan">
          <param name="gateway-url" value="http://backend-api:3000/api/v1/freeswitch/dialplan" bindings="dialplan"/>
          <param name="method" value="POST"/>
        </binding>
        <binding name="configuration">
          <param name="gateway-url" value="http://backend-api:3000/api/v1/freeswitch/configuration" bindings="configuration"/>
          <param name="method" value="POST"/>
        </binding>
      </bindings>
    </configuration>