apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeswitch-server
  namespace: ai-receptionist
  labels:
    app: freeswitch-server
    component: telephony-core
spec:
  replicas: 1
  strategy:
    type: Recreate  # FreeSWITCH needs exclusive port binding
  selector:
    matchLabels:
      app: freeswitch-server
  template:
    metadata:
      labels:
        app: freeswitch-server
        component: telephony-core
    spec:
      containers:
      - name: freeswitch
        image: 176.9.65.80:5000/ai-receptionist/freeswitch-server:latest
        imagePullPolicy: Always
        ports:
        - name: sip-udp
          containerPort: 5060
          protocol: UDP
        - name: event-socket
          containerPort: 8021
          protocol: TCP
        - name: rtp-start
          containerPort: 16384
          protocol: UDP
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: freeswitch-logs
          mountPath: /var/log/freeswitch
        - name: freeswitch-data
          mountPath: /var/lib/freeswitch
        livenessProbe:
          tcpSocket:
            port: 8021
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8021
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          tcpSocket:
            port: 8021
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      volumes:
      - name: freeswitch-logs
        emptyDir: {}
      - name: freeswitch-data
        persistentVolumeClaim:
          claimName: freeswitch-data-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeswitch-data-pvc
  namespace: ai-receptionist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage