apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeswitch
  namespace: ai-receptionist
  labels:
    app: freeswitch
    component: telephony
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: freeswitch
  template:
    metadata:
      labels:
        app: freeswitch
        component: telephony
    spec:
      containers:
      - name: freeswitch
        image: ai-receptionist/freeswitch:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: sip-udp
          containerPort: 5060
          protocol: UDP
        - name: api-http
          containerPort: 8080
          protocol: TCP
        - name: rtp-start
          containerPort: 16384
          protocol: UDP
        env:
        - name: AI_ENGINE_URL
          value: "http://ai-engine:8000"
        - name: BACKEND_API_URL
          value: "http://backend-api:3000/api/v1"
        - name: FREESWITCH_LOG_LEVEL
          value: "INFO"
        - name: SIP_PORT
          value: "5060"
        - name: RTP_PORT_MIN
          value: "16384"
        - name: RTP_PORT_MAX
          value: "32768"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: freeswitch-config
          mountPath: /app/config
          readOnly: true
        - name: freeswitch-logs
          mountPath: /app/logs
        - name: freeswitch-data
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      volumes:
      - name: freeswitch-config
        configMap:
          name: freeswitch-config
      - name: freeswitch-logs
        emptyDir: {}
      - name: freeswitch-data
        persistentVolumeClaim:
          claimName: freeswitch-data-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      serviceAccountName: freeswitch-service-account
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeswitch-data-pvc
  namespace: ai-receptionist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: freeswitch-service-account
  namespace: ai-receptionist
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ai-receptionist
  name: freeswitch-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: freeswitch-role-binding
  namespace: ai-receptionist
subjects:
- kind: ServiceAccount
  name: freeswitch-service-account
  namespace: ai-receptionist
roleRef:
  kind: Role
  name: freeswitch-role
  apiGroup: rbac.authorization.k8s.io