apiVersion: v1
kind: Service
metadata:
  name: freeswitch-sip
  namespace: ai-receptionist
  labels:
    app: freeswitch-server
    service-type: sip
  annotations:
    metallb.universe.tf/allow-shared-ip: "ai-receptionist-shared"
spec:
  type: LoadBalancer
  loadBalancerIP: 88.198.85.74
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
  - name: sip-udp
    port: 5060
    targetPort: 5060
    protocol: UDP
  selector:
    app: freeswitch-server
---
apiVersion: v1
kind: Service
metadata:
  name: freeswitch-rtp
  namespace: ai-receptionist
  labels:
    app: freeswitch-server
    service-type: rtp
  annotations:
    metallb.universe.tf/allow-shared-ip: "ai-receptionist-shared"
spec:
  type: LoadBalancer
  loadBalancerIP: 88.198.85.74
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
  # RTP port range - in production, you might want to limit this range
  - name: rtp-16384
    port: 16384
    targetPort: 16384
    protocol: UDP
  - name: rtp-16385
    port: 16385
    targetPort: 16385
    protocol: UDP
  - name: rtp-16386
    port: 16386
    targetPort: 16386
    protocol: UDP
  - name: rtp-16387
    port: 16387
    targetPort: 16387
    protocol: UDP
  - name: rtp-16388
    port: 16388
    targetPort: 16388
    protocol: UDP
  # Add more RTP ports as needed for concurrent calls
  # For production, consider using a range or separate service per pod
  selector:
    app: freeswitch-server
---
apiVersion: v1
kind: Service
metadata:
  name: freeswitch-event-socket
  namespace: ai-receptionist
  labels:
    app: freeswitch-server
    service-type: event-socket
spec:
  type: ClusterIP
  ports:
  - name: event-socket
    port: 8021
    targetPort: 8021
    protocol: TCP
  selector:
    app: freeswitch-server
---
# Headless service for internal pod discovery
apiVersion: v1
kind: Service
metadata:
  name: freeswitch-headless
  namespace: ai-receptionist
  labels:
    app: freeswitch-server
    service-type: headless
spec:
  clusterIP: None
  ports:
  - name: event-socket
    port: 8021
    targetPort: 8021
    protocol: TCP
  selector:
    app: freeswitch-server
  ports:
  - name: sip-udp
    port: 5060
    targetPort: 5060
    protocol: UDP
  - name: http-api
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: freeswitch