apiVersion: v1
kind: Pod
metadata:
  name: freeswitch-test
  namespace: ai-receptionist
spec:
  containers:
  - name: freeswitch-test
    image: 176.9.65.80:5000/ai-receptionist/freeswitch-server:latest
    command: ["sleep", "3600"]
    volumeMounts:
    - name: freeswitch-config
      mountPath: /etc/freeswitch
  volumes:
  - name: freeswitch-config
    configMap:
      name: freeswitch-config
  restartPolicy: Never
