apiVersion: v1
kind: Pod
metadata:
  name: freeswitch-test-subpath
  namespace: ai-receptionist
spec:
  containers:
  - name: freeswitch-test
    image: 176.9.65.80:5000/ai-receptionist/freeswitch-server:latest
    command: ["sleep", "3600"]
    volumeMounts:
    - name: freeswitch-config
      mountPath: /etc/freeswitch/modules.conf.xml
      subPath: modules.conf.xml
    - name: freeswitch-config
      mountPath: /etc/freeswitch/xml_curl.conf.xml
      subPath: xml_curl.conf.xml
    - name: freeswitch-config
      mountPath: /etc/freeswitch/ai_receptionist.xml
      subPath: ai_receptionist.xml
    - name: freeswitch-config
      mountPath: /etc/freeswitch/event_socket.conf.xml
      subPath: event_socket.conf.xml
    - name: freeswitch-config
      mountPath: /etc/freeswitch/sofia.conf.xml
      subPath: sofia.conf.xml
    - name: freeswitch-config
      mountPath: /etc/freeswitch/switch.conf.xml
      subPath: switch.conf.xml
  volumes:
  - name: freeswitch-config
    configMap:
      name: freeswitch-config
  restartPolicy: Never
