apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ai-receptionist
  labels:
    app: ollama
    component: ai-engine
spec:
  replicas: 1
  strategy:
    type: Recreate  # Ollama needs exclusive access to models
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
        component: ai-engine
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0:11434"
        - name: OLLAMA_ORIGINS
          value: "*"  # Allow requests from any origin within cluster
        - name: OLLAMA_MODELS
          value: "/root/.ollama/models"
        # For GPU support, uncomment these:
        # - name: OLLAMA_NUM_GPU
        #   value: "1"
        # - name: OLLAMA_GPU_LAYERS
        #   value: "35"  # Number of layers to offload to GPU
        resources:
          requests:
            memory: "4Gi"   # Minimum for running 7B models
            cpu: "2000m"
          limits:
            memory: "16Gi"  # Larger models need more RAM
            cpu: "8000m"
            # For GPU support, add:
            # nvidia.com/gpu: "1"
        volumeMounts:
        - name: ollama-models
          mountPath: /root/.ollama/models
        - name: ollama-data
          mountPath: /root/.ollama
        livenessProbe:
          httpGet:
            path: /
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 11434
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 11434
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30  # Give it 5 minutes to start and load models
      volumes:
      - name: ollama-models
        persistentVolumeClaim:
          claimName: ollama-models-pvc
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
