apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ai-receptionist
  labels:
    app: ollama
    component: ai-engine
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
  - name: http
    port: 11434
    targetPort: 11434
    protocol: TCP
  sessionAffinity: ClientIP  # Maintain session for streaming responses
---
# Optional: NodePort for external access during development/testing
apiVersion: v1
kind: Service
metadata:
  name: ollama-external
  namespace: ai-receptionist
  labels:
    app: ollama
    component: ai-engine
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
  - name: http
    port: 11434
    targetPort: 11434
    nodePort: 30434  # Access via http://<node-ip>:30434
    protocol: TCP
