# Request the cert explicitly
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontmind-cert
  namespace: ai-receptionist
spec:
  secretName: frontmind-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - frontmind.mobiletel.eu